<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="ErrorValidation(failed)">
    <classes>
      <class name="TestCases.ErrorValidationTest">
        <methods>
          <include name="ErrorValidationPassword"/>
          <include name="ErrorValidationEmail"/>
          <include name="LaunchApplication"/>
          <include name="CloseBrowser"/>
        </methods>
      </class> <!-- TestCases.ErrorValidationTest -->
    </classes>
  </test> <!-- ErrorValidation(failed) -->
  <test thread-count="5" name="PlaceOrder(failed)">
    <classes>
      <class name="TestCases.PlaceOrderEndToEndTest">
        <methods>
          <include name="LaunchApplication"/>
          <include name="CloseBrowser"/>
          <include name="OrderHistoryTest"/>
          <include name="PlaceOrder" invocation-numbers="0"/>
        </methods>
      </class> <!-- TestCases.PlaceOrderEndToEndTest -->
    </classes>
  </test> <!-- PlaceOrder(failed) -->
</suite> <!-- Failed suite [Suite] -->
